### ISSUE TITLE
No support in Vs 22

### ISSUE THREAD

**Issue by soubhi8** [madskristensen/TypeScriptDefinitionGenerator#58]
### Installed product versions
- Visual Studio:  2022 Professional
- This extension: 1.3.53

### Description
no support in vs 22

### Steps to recreate
install the tool
restart vs 22 

### Current behavior
the option to generate .ts file is absent when right-clicking or in settings

### Expected behavior
the option to generate .ts should appear

**Comment by menees** [comment]
Agreed. It's not working in VS 2022 17.0.2 for anyone on my team. Going to the Tools > Options > Text Editor > JavaScript/TypeScript > Generate d.ts screen pops up an error dialog:

```
---------------------------
Microsoft Visual Studio
---------------------------
The 'DtsPackage' package did not load correctly.

The problem may have been caused by a configuration change or by the installation of another extension. You can get more information by examining the file 'C:\Users\btm\AppData\Roaming\Microsoft\VisualStudio\17.0_765cfe16\ActivityLog.xml'.

Restarting Visual Studio could help resolve this issue.

Continue to show this error message?
---------------------------
Yes   No   
---------------------------
```
I've attached a zip file of my ActivityLog.xml. The most relevant error is early on:

```
Still unable to load MEF component DLL: Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.VSHost.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
          C:\USERS\BTM\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_765CFE16\EXTENSIONS\AFCK4LST.CVA\TypeScriptDefinitionGenerator.dll
Source: Microsoft.VisualStudio.ComponentModelHost.VsShellComponentModelHost
```

Then when I try to open the "Generate d.ts" options screen the failure manifests as:

```
LegacySitePackage failed for package [DtsPackage]Source: 'mscorlib' Description: Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.VSHost.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.VSHost.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TextTemplating.VSHost.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at Microsoft.VisualStudio.Shell.Package.ScheduleToolboxItemDiscoveryFactoriesRegistrationIfNecessary()
   at Microsoft.VisualStudio.Shell.Package.Initialize()
   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

<guid>{D1E45432-D98B-4053-B3D7-E16D258C2959}</guid>
<hr>80070002</hr>
```

[ActivityLog.zip](https://github.com/madskristensen/TypeScriptDefinitionGenerator/files/7660923/ActivityLog.zip)

**Comment by happywisepaul** [comment]
I experienced exactly the same thing as user **menees**, with exactly the same error in ActivityLog.xml.  With Visual Studio 2022 version 17.0.2 as well.  Going to Tools -> Options -> Text Editor -> JavaScript/TypeScript -> Generate d.ts also triggered the same error dialog box.

**Comment by trontronicent** [comment]
I cloned the repo, and within a couple of hours, I managed to get it at least work with a simple test class within a AspNetCore 6.0 project. Its pretty difficult for me, never worked on VS extensions and a lot of code locations where exceptions occur i cannot see the source. One of the issues (easy fix), are missing and/or changed Visual Studio project type GUIDs, but also some Threading errors - seems like there have been some quite radical changes from 2019 to 2022, as the code has - according to the analysis, quite many problematic zones.

Ill have to test with all the other project types, add the guids, and fix these thread issues - can't say how long it will take, as I have to do it in my rare spare time, but as I need this extension working on 2022, i'll keep working on it ^^

**Comment by neozhu** [comment]
I create a new project based on this repo, it's working on visual studio 2022
https://github.com/neozhu/CleanArchitectureCodeGenerator

**Comment by telinden** [comment]
Still not working?
